DROP INDEX I_PK_PERSONNE;

DROP INDEX I_FK_PERSONNE_NIVEAU;

DROP INDEX I_PK_FACTURE;

DROP INDEX I_FK_FACTURE_PERSONNE;

DROP INDEX I_FK_FACTURE_FORFAIT;

DROP INDEX I_PK_FORFAIT;

DROP INDEX I_PK_ENTRAINEMENT;

DROP INDEX I_FK_ENTRAINEMENT_TERRAIN;

DROP INDEX I_FK_ENTRAINEMENT_PERSONNE;

DROP INDEX I_PK_TYPE_TERRAIN;

DROP INDEX I_PK_TERRAIN;

DROP INDEX I_FK_TERRAIN_TYPE_TERRAIN;

DROP INDEX I_PK_CRENEAU;

DROP INDEX I_FK_CRENEAU_TERRAIN;

DROP INDEX I_FK_CRENEAU_ENTRAINEMENT;

DROP INDEX I_PK_RESERVATION;

DROP INDEX I_FK_RESERVATION_FACTURE;

DROP INDEX I_FK_RESERVATION_CRENEAU;

DROP INDEX I_FK_RESERVATION_PERSONNE;

DROP INDEX I_PK_NIVEAU;

DROP INDEX I_PK_PARTICIPER;

DROP INDEX I_FK_PARTICIPER_PERSONNE;

DROP INDEX I_FK_PARTICIPER_RESERVATION;

DROP INDEX I_PK_ENTRAINER;

DROP INDEX I_FK_ENTRAINER_NIVEAU;

DROP INDEX I_FK_ENTRAINER_PERSONNE;

DROP INDEX I_PK_SOUSCRIRE;

DROP INDEX I_FK_SOUSCRIRE_PERSONNE;

DROP INDEX I_FK_SOUSCRIRE_FORFAIT;

DROP INDEX I_PK_ASSISTER;

DROP INDEX I_FK_ASSISTER_PERSONNE;

DROP INDEX I_FK_ASSISTER_ENTRAINEMENT;