
-- -----------------------------------------------------------------------------
--       CREATION DES REFERENCES DE TABLE
-- -----------------------------------------------------------------------------


ALTER TABLE PERSONNE ADD (
     CONSTRAINT FK_PERSONNE_NIVEAU
          FOREIGN KEY (NUMERO_NIVEAU)
               REFERENCES NIVEAU (NUMERO_NIVEAU))   ;

ALTER TABLE FACTURE ADD (
     CONSTRAINT FK_FACTURE_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE FACTURE ADD (
     CONSTRAINT FK_FACTURE_FORFAIT
          FOREIGN KEY (NUMERO_FORFAIT)
               REFERENCES FORFAIT (NUMERO_FORFAIT))   ;

ALTER TABLE ENTRAINEMENT ADD (
     CONSTRAINT FK_ENTRAINEMENT_TERRAIN
          FOREIGN KEY (NOM_TERRAIN)
               REFERENCES TERRAIN (NOM_TERRAIN))   ;

ALTER TABLE ENTRAINEMENT ADD (
     CONSTRAINT FK_ENTRAINEMENT_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE TERRAIN ADD (
     CONSTRAINT FK_TERRAIN_TYPE_TERRAIN
          FOREIGN KEY (NUM_TYPE_TERRAIN)
               REFERENCES TYPE_TERRAIN (NUM_TYPE_TERRAIN))   ;

ALTER TABLE CRENEAU ADD (
     CONSTRAINT FK_CRENEAU_TERRAIN
          FOREIGN KEY (NOM_TERRAIN)
               REFERENCES TERRAIN (NOM_TERRAIN))   ;

ALTER TABLE CRENEAU ADD (
     CONSTRAINT FK_CRENEAU_ENTRAINEMENT
          FOREIGN KEY (NUM_ENTRAINEMENT)
               REFERENCES ENTRAINEMENT (NUM_ENTRAINEMENT))   ;

ALTER TABLE RESERVATION ADD (
     CONSTRAINT FK_RESERVATION_FACTURE
          FOREIGN KEY (NUMERO_FACTURE)
               REFERENCES FACTURE (NUMERO_FACTURE))   ;

ALTER TABLE RESERVATION ADD (
     CONSTRAINT FK_RESERVATION_CRENEAU
          FOREIGN KEY (NOM_TERRAIN, DATE_CRENEAU, HORAIRE_CRENEAU)
               REFERENCES CRENEAU (NOM_TERRAIN, DATE_CRENEAU, HORAIRE_CRENEAU))   ;

ALTER TABLE RESERVATION ADD (
     CONSTRAINT FK_RESERVATION_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE PARTICIPER ADD (
     CONSTRAINT FK_PARTICIPER_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE PARTICIPER ADD (
     CONSTRAINT FK_PARTICIPER_RESERVATION
          FOREIGN KEY (NUMERO_RESERVATION)
               REFERENCES RESERVATION (NUMERO_RESERVATION))   ;

ALTER TABLE ENTRAINER ADD (
     CONSTRAINT FK_ENTRAINER_NIVEAU
          FOREIGN KEY (NUMERO_NIVEAU)
               REFERENCES NIVEAU (NUMERO_NIVEAU))   ;

ALTER TABLE ENTRAINER ADD (
     CONSTRAINT FK_ENTRAINER_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE SOUSCRIRE ADD (
     CONSTRAINT FK_SOUSCRIRE_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE SOUSCRIRE ADD (
     CONSTRAINT FK_SOUSCRIRE_FORFAIT
          FOREIGN KEY (NUMERO_FORFAIT)
               REFERENCES FORFAIT (NUMERO_FORFAIT))   ;

ALTER TABLE ASSISTER ADD (
     CONSTRAINT FK_ASSISTER_PERSONNE
          FOREIGN KEY (NUMERO_PERSONNE)
               REFERENCES PERSONNE (NUMERO_PERSONNE))   ;

ALTER TABLE ASSISTER ADD (
     CONSTRAINT FK_ASSISTER_ENTRAINEMENT
          FOREIGN KEY (NUM_ENTRAINEMENT)
               REFERENCES ENTRAINEMENT (NUM_ENTRAINEMENT))   ;