
   DROP SEQUENCE  "SEQNUMFORFAIT" ;
   
   DROP SEQUENCE  "SEQNUMFACTURE" ;

   DROP SEQUENCE  "SEQNUMPERSONNE" ; 

   DROP SEQUENCE  "SEQNUMRESERVATION" ; 

   DROP SEQUENCE  "SEQNUMENTRAINEMENT"; 

   DROP SEQUENCE  "SEQNUMNIVEAU" ;

   DROP SEQUENCE  "SEQNUMTYPETERRAIN" ;