DROP TABLE PERSONNE CASCADE CONSTRAINTS;

DROP TABLE FACTURE CASCADE CONSTRAINTS;

DROP TABLE FORFAIT CASCADE CONSTRAINTS;

DROP TABLE ENTRAINEMENT CASCADE CONSTRAINTS;

DROP TABLE TYPE_TERRAIN CASCADE CONSTRAINTS;

DROP TABLE TERRAIN CASCADE CONSTRAINTS;

DROP TABLE CRENEAU CASCADE CONSTRAINTS;

DROP TABLE RESERVATION CASCADE CONSTRAINTS;

DROP TABLE NIVEAU CASCADE CONSTRAINTS;

DROP TABLE PARTICIPER CASCADE CONSTRAINTS;

DROP TABLE ENTRAINER CASCADE CONSTRAINTS;

DROP TABLE SOUSCRIRE CASCADE CONSTRAINTS;

DROP TABLE ASSISTER CASCADE CONSTRAINTS;