-- ===================================================================================================================
--							INSERTION DES DATA
-- ===================================================================================================================

--- FORFAITS

INSERT INTO FORFAIT ( NUMERO_FORFAIT, DESIGNATION_FORFAIT,PRIX_FORFAIT, NOMBRE_HEURE_FORFAIT, DUREE_VAL_FORFAIT ) VALUE (0 ,'Sans forfait', 0, 0, 0);

--- NIVEAUX

INSERT INTO NIVEAU (NUMERO_NIVEAU, NOM_NIVEAU) VALUES (2 , 'Niveau 2');
INSERT INTO NIVEAU (NUMERO_NIVEAU, NOM_NIVEAU) VALUES (1 , 'Niveau 1');		

--- PERSONNES 

--- ENTRAINEUR
	
INSERT INTO PERSONNE (NUMERO_PERSONNE ,NOM_PERSONNE, PRENOM_PERSONNE , NUMERO_NIVEAU , NAISSANCE_PERSONNE , TELEPHONE_PERSONNE , NUMERO_ADD_PERSONNE , RUE_PERSONNE , CP_PERSONNE , VILLE_PERSONNE , PAYS_PERSONNE , ROLE_PERSONNE , USER_PERSONNE , MDP_PERSONNE ,  DATE_EMBAUCHE_ENTRAINEUR , SALAIRE_ENTRAINEUR) VALUES ( 0 ,'BENO', 'Matt' , 0 ,'07/08/1990' , '0617490567' , 41 , 'Paul', '90000' , 'BELFORT' , 'FRANCE' , 'Entraineur', 'BENO' , mp.encrypt('12456') , '27/05/2018' , 2000 );

INSERT INTO PERSONNE (NUMERO_PERSONNE ,NOM_PERSONNE, PRENOM_PERSONNE , NUMERO_NIVEAU, NAISSANCE_PERSONNE , TELEPHONE_PERSONNE , NUMERO_ADD_PERSONNE , RUE_PERSONNE , CP_PERSONNE , VILLE_PERSONNE , PAYS_PERSONNE , ROLE_PERSONNE , USER_PERSONNE , MDP_PERSONNE ,  DATE_EMBAUCHE_ENTRAINEUR , SALAIRE_ENTRAINEUR) VALUES (1, 'CODERT','Ben', 1 , '09/01/2004' , '0615478975' , 2 , 'Marcel ', '90000' , 'BELFORT' , 'FRANCE' , 'Entraineur', 'CODERT' , mp.encrypt('12456') , '27/05/2018' ,2000);


--- JOUEURS

INSERT INTO PERSONNE (NUMERO_PERSONNE ,NOM_PERSONNE, PRENOM_PERSONNE , NUMERO_NIVEAU, NAISSANCE_PERSONNE , TELEPHONE_PERSONNE , NUMERO_ADD_PERSONNE , RUE_PERSONNE , CP_PERSONNE , VILLE_PERSONNE , PAYS_PERSONNE , ROLE_PERSONNE , USER_PERSONNE , MDP_PERSONNE , NUM_ENTRAINEUR) VALUES (2,'KHAYECHE', 'Nesrine' , 1, '07/08/1995' , '0617490567' , 3 , 'Marcel Paul', '90000' , 'BELFORT' , 'FRANCE' , 'Joueur', 'KHAYECHE' , mp.encrypt('12456') , 1 );

INSERT INTO PERSONNE (NUMERO_PERSONNE ,NOM_PERSONNE, PRENOM_PERSONNE , NUMERO_NIVEAU, NAISSANCE_PERSONNE , TELEPHONE_PERSONNE , NUMERO_ADD_PERSONNE , RUE_PERSONNE , CP_PERSONNE , VILLE_PERSONNE , PAYS_PERSONNE , ROLE_PERSONNE , USER_PERSONNE , MDP_PERSONNE , NUM_ENTRAINEUR) VALUES (3,'GODERT', 'Alexia' ,0, '06/01/2001' , '0615478975' , 7 , 'Gaston', '90000' , 'BELFORT' , 'FRANCE' , 'Joueur', 'GODERT' , mp.encrypt('12456') , 0 );

--- SOUSCRIRE

INSERT INTO SOUSCRIRE (NUMERO_PERSONNE,NUMERO_FORFAIT) VALUES (0 ,0);

INSERT INTO SOUSCRIRE (NUMERO_PERSONNE,NUMERO_FORFAIT) VALUES (1 ,0);

INSERT INTO SOUSCRIRE (NUMERO_PERSONNE,NUMERO_FORFAIT) VALUES (2 ,0);

INSERT INTO SOUSCRIRE (NUMERO_PERSONNE,NUMERO_FORFAIT) VALUES (3 ,0);


--- ENTRAINEMENT

INSERT INTO ENTRAINEMENT (NUM_ENTRAINEMENT, NOM_TERRAIN , NUMERO_PERSONNE, TYPE_ENTRAINEMENT , FREQUENCE_ENTRAINEMENT , NBR_MAX_PARTICIPANTS , DEBUT_ENTRAINEMENT , FIN_ENTRAINEMENT) VALUES (1,'Monte_carlo', 0, 'Collectif' , '10' , 1 , '30/05/2018' , '25/06/2018' );
INSERT INTO ENTRAINEMENT (NUM_ENTRAINEMENT, NOM_TERRAIN , NUMERO_PERSONNE, TYPE_ENTRAINEMENT , FREQUENCE_ENTRAINEMENT , NBR_MAX_PARTICIPANTS , DEBUT_ENTRAINEMENT , FIN_ENTRAINEMENT) VALUES (2,'Monte_carlo', 2, 'Collectif' , '10', 1 , '30/06/2018' , '25/07/2018' );

--- CRENEAU

INSERT INTO CRENEAU (NOM_TERRAIN, DATE_CRENEAU, HORAIRE_CRENEAU, DUREE_CRENEAU , NUM_ENTRAINEMENT ) VALUES ('Terrain_2', '30/05/2018' , '17:00:00', '2', 1) ;
INSERT INTO CRENEAU (NOM_TERRAIN, DATE_CRENEAU, HORAIRE_CRENEAU, DUREE_CRENEAU , NUM_ENTRAINEMENT ) VALUES ('Terrain_1', '30/06/2018' , '17:00:00', '2', 2) ;
INSERT INTO CRENEAU (NOM_TERRAIN, DATE_CRENEAU, HORAIRE_CRENEAU, DUREE_CRENEAU , NUM_ENTRAINEMENT ) VALUES ('Terrain_1', '30/06/2018' , '07:00:00', '2', null) ;

--- TERRAINS

INSERT INTO TERRAIN (NOM_TERRAIN, NUM_TYPE_TERRAIN, DESCRIPTION_TERRAIN) VALUES ('ABC', 1 , 'ABC');
INSERT INTO TERRAIN (NOM_TERRAIN, NUM_TYPE_TERRAIN, DESCRIPTION_TERRAIN) VALUES ('Monte_carlo', 0 , 'Outdoor');

--- TYPE_TERRAIN

INSERT INTO TYPE_TERRAIN (NUM_TYPE_TERRAIN, DESIGNATION_TYPE_TERRAIN) VALUES (1, 'Terre battue');
INSERT INTO TYPE_TERRAIN (NUM_TYPE_TERRAIN, DESIGNATION_TYPE_TERRAIN) VALUES (0, 'GAZON');


--- ASSISTER

INSERT INTO ASSISTER (NUMERO_PERSONNE , NUM_ENTRAINEMENT ) VALUES (0 , 1) ;
INSERT INTO ASSISTER (NUMERO_PERSONNE , NUM_ENTRAINEMENT ) VALUES (1 , 2) ;

--- ENTRAINER

INSERT INTO ENTRAINER (NUMERO_NIVEAU, NUMERO_PERSONNE) VALUES (0, 0);
INSERT INTO ENTRAINER (NUMERO_NIVEAU, NUMERO_PERSONNE) VALUES (1, 1);

--- FACTURE

insert into FACTURE (NUMERO_FACTURE,NUMERO_FORFAIT, NUMERO_PERSONNE, DATE_FACTURE,MONTANT_FACTURE) values (224, 0, 0, '16/06/18', 5);

--- RESERVATION

insert into RESERVATION (NUMERO_RESERVATION,NUMERO_FACTURE,DATE_CRENEAU,HORAIRE_CRENEAU,NUMERO_PERSONNE,NOM_TERRAIN,DATE_RESERVATION,PRIX_RESERVATION,NOM_PERSONNE,PRENOM_PERSONNE) values (160,224,'12/06/18','12/06/18' , 0 , 'ABC' , '16/06/18', 5 ,'BENO', 'Matt');

--- PARTCIPER

insert into PARTICIPER (NUMERO_PERSONNE , NUMERO_RESERVATION) values (0, 160);
